### PR TITLE
Migrate Travis to the new container-based infrastructure

### PR DESCRIPTION
**Pull request by winstliu**
:racehorse: :dash: :zap: 3000% faster build times!  Also greatly simplified the build.

@WildCard65 asked me to do this.

### CODE REVIEW

**Comment by winstliu** [comment]
Question: Some of the includes that you're bundling in this repo can be accessed remotely-would you rather that those are removed and instead downloaded each time through Travis?

**Comment by sarabveer** [comment]
Weird, this one runs for 50secs, while the old one only runs for 20-30sec.

**Comment by WildCard65** [comment]
It might be from DDos github is being attacked with.

**Comment by sarabveer** [comment]
I just need the include for SteamWorks.

**Comment by WildCard65** [comment]
Scratch my previous comment, it was this command that added the extra seconds: sudo -E apt-get -yq update &>> ~/apt-get-update.log  
The command is executed by travis itself.

**Comment by winstliu** [comment]
I'll fix the conflict later(TM).

**Comment by winstliu** [comment]
Ok, time to delete this fork and try again.

**Pull request closed without merging**
