### PR TITLE
Fix negative values being accepted in ban commands (solve issue #949)

### PR DESCRIPTION
**Pull request by sunstep**
## Description

The changes add a check on all ban commands to see whether the given duration is 0 or more. If the duration given is smaller than zero, it will tell the player and the ban will not proceed.

## Motivation and Context

The motivation behind this pull request is that this fixes an open issue. Issue #949. According to the issue, banning with a negative time value is useless and only bans the player for the session. With this pull request banning with a negative value should not be possible anymore

## How Has This Been Tested?

The changes have been tested on my own community server on a real player. When entering a negative value, we want the entire command to stop after giving the command issuer a warning. This approach should be valid and should not affect any other areas in the code. Values of 0 or higher have also been tested and these do get accepted by the command.

## Screenshots (if appropriate):
image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Rushaway** [comment]
You can keep it DRY with the existing code.
```sp
if (!StringToIntEx(buffer, time) || time < 0)
{
    ReplyToCommand(client, "%sUsage: sm_ban <#userid|name> <time|0> [reason]", Prefix);
    return Plugin_Handled;
}
```
Edit: Also please keep using tranlations, sourcebanspp is used by tons of users.

**Comment by sunstep** [comment]
Implemented this way for the CommandBan function, will add more new commits soon

**Comment by Rushaway** [comment]
It should also apply to every changes you made.

**Comment by sunstep** [comment]
I don't see how it is possible in the other parts. The other parts don't print the right message after getting the int value of time. And since the minutes variable is used multiple times, wouldn't it be better there to just leave a separate check for if the time is negative or not?

Next to that, I can add translations for this phrase. But only when all other issues with the code I provided are resolved.

**Comment by Rushaway** [comment]
To avoid create new translations, we can just stick to the current command usage phrase. 
Adjust the reply to cmd to the function ofc.
```sp
if (!StringToIntEx(time, minutes) || minutes < 0)
{
    ReplyToCommand(client, "%sUsage: sm_banip <#userid|name> <time> [reason]", Prefix);
    return Plugin_Handled;
}
```

**Comment by sunstep** [comment]
Done, the approach is now used for all commands.

**Comment by sunstep** [comment]
By the way, should the sourcebans version be bumped? I decided not to do it, just in case. I can always add a commit if needed.

**Comment by Rushaway** [comment]
LGTM. 
No need to bump version, we will release a new version with all recent commits soon.

**Comment by Hackmastr** [comment]
Thanks @Rushaway @sunstep!

**Pull request merged**
