### PR TITLE
Comm block length colouring

### PR DESCRIPTION
**Pull request by obtoon**
Home page and banlist both have it, adding it to comms page.

### CODE REVIEW

**Comment by kilroy98** [comment]
on comms page lenght not colouring =((

**Comment by obtoon** [comment]
Have you updated your SourceBans installation?

**Comment by kilroy98** [comment]
@presskoala i download SourceBans from you page

**Comment by sarabveer** [comment]
What version?

**Comment by kilroy98** [comment]
SourceBans++ 1.5.4-dev-git290

**Comment by sarabveer** [comment]
Get the latest one.

**Comment by kilroy98** [comment]
Now is colouring, sorry for disturb =)

**Pull request merged**
