### PR TITLE
Improve File Warning Message

### PR DESCRIPTION
**Pull request by stickz**

### CODE REVIEW

**Comment by sarabveer** [comment]
Not needed

**Comment by stickz** [comment]
The last warning message I created was horrible. And is missing a critical element relating to file syntax.

Edit: PR #127 and #128. This feature was added by myself to catch an invalid handle. And communicate to the user the actual plugin with the white list file.

**Comment by sarabveer** [comment]
its the same and is uneeded

**Comment by stickz** [comment]
"Incorrect Formatting" is anther issue which causes the invalid handle. Like if the user accidentally removes a bracket or puts something into the file which shouldn't be there. This was not communicated properly by the previous pull request which introduced the warning message.

**Comment by sarabveer** [comment]
this seriously is not a plugin breaking issue.

**Pull request closed without merging**
