### PR TITLE
SourceComm Dashboard Support

### PR DESCRIPTION
**Pull request by obtoon**
Adds a module to the dashboard which shows the latest comm blocks, had to do some rearranging to make it fit. This is what it ends up looking like:

Quite a drastic change so obviously no pressure to add it. This is just directly from a modification I made to mine, so I haven't edited all the included themes.

### CODE REVIEW

**Comment by sarabveer** [comment]
Nice

**Comment by obtoon** [comment]
Ill add length colouring to the comms page too soon

**Comment by sarabveer** [comment]
Add Coloring to the Bans page too, my job was a quick and dirty one.

**Comment by 404UserNotFound** [comment]
coloring is already on the bans page because i did it: http://www.unfgaming.net/bans/index.php?p=banlist

**Comment by 404UserNotFound** [comment]
correction for Enstage: apparently Veer may have done my banlist page coloration wrong (even though the code looks proper to me and should by all rights work) so look into that as well.

Veer: do you even have custom BG colors defined in your CSS for the listtable_1_permanent/etc classes?

**Comment by sarabveer** [comment]
I have no clue, all I did was add your code.

I haven't tested it yet. That's why I'm unsure if it works.

**Comment by 404UserNotFound** [comment]
Nevermind! Veer just hasn't tested it and isn't sure if it works apparently, even though it works on mine (I edited a guys ban for the preview image to show that it does work)

**Comment by obtoon** [comment]
I only installed SourceBans++ on my community 3 days ago (from this repo), bans page had colouring. I'll add colouring to the comms page as well.

**Pull request merged**
