### PR TITLE
Update SourceQuery library version

### LINKED ISSUE #733: Server are not showing.
source :
https://forums.alliedmods.net/showthread.php?t=332524

Recently suddenly, server list are not showing.
Windows Server only has this problem.
sombody help me~
" [+] Got an response! Server: "
Server name(hostname) is not showing.

[+] SourceBans "Error Connecting()" Debug starting for server 112.154.xxx.xxx:27015

[+] Trying to establish UDP connection
[+] UDP connection successfull!
[+] Trying to write to the socket
[+] Successfully requested server info. (That doesn't mean anything on an UDP stream.) Reading...
[+] Got an response! Server:

[+] Trying to establish TCP connection
[+] TCP connection successfull!
[+] Trying to write to TCP socket and authenticate via rcon
[+] Successfully sent authentication request. Reading...
[+] Got an response!
[+] Password correct!

### LINKED ISSUE #734: No support for a2s challenge - Update SourceQuery include
Update SourceQuery to fix issues with the new a2s challenge that has been added to srcds.

https://github.com/xPaw/PHP-Source-Query/blob/cd3624704ebd2ef6f6b21cb139e3b82a9e866147/SourceQuery/SourceQuery.php

Probably fixes #733

Info here:
https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO
https://steamcommunity.com/discussions/forum/14/2974028351344359625/

Servers can now 'challenge' a2s queries, requiring an additional response with the 4 byte challenge added to the end of the query.
This breaks sourcebans because the outdated SourceQuery doesn't handle challenges.

Example:
you send `FF FF FF FF 54 "Source Engine Query\0"`
the server responds back: `FF FF FF FF 41 (4 byte challenge here)`
then you have to reply `FF FF FF FF 54 "Source Engine Query\0" (4 byte challenge)`
server then provides requested info

What are the steps to reproduce this issue?
-------------------------------------------
1. Install sbpp
2. Set EnvVar STEAM_GAMESERVER_A2S_INFO_REQUIRE_CHALLENGE=1
3. Reboot game server(s)
4. Check sourcebans page and notice it doesnt receive info from servers. (It didn't respond to the a2s challenge)

What happens?
-------------
Server info doesnt show on sb web if STEAM_GAMESERVER_A2S_INFO_REQUIRE_CHALLENGE env var set to 1 for server(s)

What were you expecting to happen?
----------------------------------
Server info should show lol

Any logs, error output, etc.?
----------------------------

Any other comments?
-------------------
Update SourceQuery

What versions of software are you using?
----------------------------------------
**Operating System:**
**SourceBans++ Version:**
**SourceMod Version:**
**MetaMod Version:**

### PR DESCRIPTION
**Pull request by Groruk**
## Description

This PR updates the SourceQuery library used to the latest version, to support the new S2C_CHALLENGE packet. (https://developer.valvesoftware.com/wiki/Server_queries#A2S_INFO)

Fixes #734 
Fixes #733

Also, with this PR the GMP extension has also been made mandatory to run the sbpp webpanel, this will give us some further library options in the future, like the SteamID library (https://github.com/xPaw/SteamID.php)

## Side effect

The newest SourceQuery version requires PHP version 7.4 or higher, this means the minimum PHP version requirement in sbpp will be bumped to 7.4

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by jjambo789** [comment]
If I update to the newest PHP and MySQL version, Is it possible to migrate MySQL data from previous versions? (my current MySQL version 5.7 / PHP version 5.6)

Sorry, I am not good at English.

**Comment by xLeviNx** [comment]
Running into these errors:

`Fatal error: Uncaught Error: Class 'xPaw\SourceQuery\SourceQuery' not found in /home/supercen/public_html/sourcebans/includes/sb-callback.php:1386 Stack trace: #0 /home/supercen/public_html/sourcebans/includes/xajax.inc.php(1090): ServerHostPlayers('29', 'servers', '', '3', '-1', '1', '70') #1 /home/supercen/public_html/sourcebans/includes/xajax.inc.php(739): xajax->_callFunction('ServerHostPlaye...', Array) #2 /home/supercen/public_html/sourcebans/index.php(24): xajax->processRequests() #3 {main} thrown in /home/supercen/public_html/sourcebans/includes/sb-callback.php on line 1386
You have whitespace in your response.`

**Comment by Groruk** [comment]
> 
> 
> If I update to the newest PHP and MySQL version, Is it possible to migrate MySQL data from previous versions? (my current MySQL version 5.7 / PHP version 5.6)
> 
> Sorry, I am not good at English.

Yes, sbpp has an updater that will update the database to the current version.
See https://sbpp.dev/docs/updating/ for more infos. (Just be sure to make a full backup of our database before updating)

**Comment by Groruk** [comment]
> 
> 
> Running into these errors:
> 
> `Fatal error: Uncaught Error: Class 'xPaw\SourceQuery\SourceQuery' not found in /home/supercen/public_html/sourcebans/includes/sb-callback.php:1386 Stack trace: #0 /home/supercen/public_html/sourcebans/includes/xajax.inc.php(1090): ServerHostPlayers('29', 'servers', '', '3', '-1', '1', '70') #1 /home/supercen/public_html/sourcebans/includes/xajax.inc.php(739): xajax->_callFunction('ServerHostPlaye...', Array) #2 /home/supercen/public_html/sourcebans/index.php(24): xajax->processRequests() #3 {main} thrown in /home/supercen/public_html/sourcebans/includes/sb-callback.php on line 1386 You have whitespace in your response.`

`SourceQuery` is now a composer dependency, so you will have to run `composer install` again to download it.

**Comment by jjambo789** [comment]
> > 최신 PHP 및 MySQL 버전으로 업데이트하면 이전 버전에서 MySQL 데이터를 마이그레이션할 수 있습니까? (내 현재 MySQL 버전 5.7 / PHP 버전 5.6)
> > 죄송합니다, 저는 영어를 잘 못합니다.
> 
> 예, sbpp에는 데이터베이스를 현재 버전으로 업데이트하는 업데이터가 있습니다.
> 자세한 내용은 https://sbpp.dev/docs/updating/ 을 참조 [하세요](https://sbpp.dev/docs/updating/) . (업데이트하기 전에 데이터베이스의 전체 백업을 만드십시오.)

Thank you so much.
I'll try it later.

**Comment by jjambo789** [comment]
> > If I update to the newest PHP and MySQL version, Is it possible to migrate MySQL data from previous versions? (my current MySQL version 5.7 / PHP version 5.6)
> > Sorry, I am not good at English.
> 
> Yes, sbpp has an updater that will update the database to the current version.
> See https://sbpp.dev/docs/updating/ for more infos. (Just be sure to make a full backup of our database before updating)

Thank you so much.
I'll try it later.

**Pull request merged**
