### PR TITLE
Add two natives to get the number of bans and comms ban of a client.

### PR DESCRIPTION
**Pull request by Sarrus1**
## Description

Added an include file and two natives for sbppchecker, which allow to get the number of bans and comms ban for a client, synchronously.

## Motivation and Context

It is useful for calladmin plugins to send information on the target, so admin can decide more easily what to do.

## How Has This Been Tested?

On the latest version of sbpp, with an external plugin which calls the native when a command is called in the server.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by DosMike** [comment]
Hey, I was looking for this feature. Nice to see I don't have to PR it now :D

**Comment by DosMike** [comment]
A forward for might be nice to have too for when data are loaded.
Maybe something like `forward void SBCheckerOnClientLoaded(int client, int gamebans, int commbans)`?

**Review by HamzaJarane — APPROVED** [review]

**Review by Rushaway — APPROVED** [review]

**Comment by ashort96** [comment]
@Sarrus1 can you rebase this to the`php81` branch?

**Review by ashort96 — APPROVED** [review]
LGTM

**Pull request merged**
