### PR TITLE
mariadb support

### PR DESCRIPTION
**Pull request by askovpen**
#60

### CODE REVIEW

**Comment by sarabveer** [comment]
No MariaDB support.

**Comment by askovpen** [comment]
merge pull request

**Comment by WildCard65** [comment]
@askovpen I think @Sarabveer means no for adding support for mariadb, I think MYSQL is only going to be supported.

**Comment by sarabveer** [comment]
Next release might have a new webpanel, that might support MariaDB.

**Comment by crasx** [comment]
I don't understand why this was rejected. Isn't mariadb a dropin replacement for mysql? There shouldn't be any differences in the queries themselves, just in the db name / version.

**Comment by sarabveer** [comment]
@crasx  Then why does that error show?

**Comment by duhow** [comment]
Despite MariaDB is a drop-in replacement for MySQL, the functions used on the PHP code are designed for MySQL. If the connector library gets updated or changed for another one that can use more DB Connectors, then MariaDB support should be added.

Until then, just use MySQL.

**Pull request closed without merging**
