### PR TITLE
Improve String Declarations

### PR DESCRIPTION
**Pull request by stickz**
Use the decl keyword instead of new to skip the initialization stage of variable declaration.

### CODE REVIEW

**Comment by stickz** [comment]
More commits to follow to this pull request.

**Comment by sarabveer** [comment]
Can you also check the commit where I made the ServerId a cvar?

https://github.com/Sarabveer/SourceBans-Fork/commit/ab091c50abbd6074dcab39b38bd0d213d541f748

**Comment by sarabveer** [comment]
Compiling sourcebans.sp...
SourcePawn Compiler 1.7.2
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2014 AlliedModders LLC
sourcebans.sp(1043) : warning 213: tag mismatch
sourcebans.sp(1186) : warning 213: tag mismatch
sourcebans.sp(1355) : warning 213: tag mismatch
sourcebans.sp(1446) : warning 213: tag mismatch
sourcebans.sp(1551) : warning 213: tag mismatch
sourcebans.sp(2330) : warning 213: tag mismatch
Code size:            49724 bytes
Data size:            16496 bytes
Stack/heap size:      16384 bytes
Total requirements:   82604 bytes

**Comment by stickz** [comment]
Yeah the ServerID commit was done incorrectly. You have to go 'serverID.IntValue' to retrieve the number from the ConVar because it's not a regular variable anymore.

Ex. To fix Line 1043

Broken
if( serverID == -1 )

Fixed
if( serverID.IntValue == -1 )

**Comment by sarabveer** [comment]
Thanks!

**Comment by sarabveer** [comment]
Compiling sbchecker.sp...
SourcePawn Compiler 1.7.2
Copyright (c) 1997-2006 ITB CompuPhase
Copyright (c) 2004-2014 AlliedModders LLC
sbchecker.sp(53) : warning 213: tag mismatch
sbchecker.sp(53) : warning 213: tag mismatch
Code size:            10404 bytes
Data size:             4528 bytes
Stack/heap size:      16384 bytes
Total requirements:   31316 bytes
2 Warnings.

**Comment by sarabveer** [comment]
That's from the previous PR you made.

**Comment by stickz** [comment]
Yeah I used an integer instead of a float for a couple CreateConVar arguments.

I'll fix that previous PR after I'm done with this one.

**Comment by stickz** [comment]
This PR is ready to be merged if there's no warnings.

**Pull request merged**
