### PR TITLE
ci: Update builders.

### PR DESCRIPTION
**Pull request by TheByKotik**
## Motivation and Context
`Treated warnings as errors (flag -E).`
Any warnings is potentially maybe issue. It is better to avoid warnings.

`Added current dir to include path ($PWD and %CD%)(flag -I<name>).`
For prevent failed build. See: https://github.com/sbpp/sourcebans-pp/pull/625

`Set low verbosity (flag -v<num>).`
Just less output info like sourcemod compiler version and `done.` message.

## How Has This Been Tested?
Tested:
1.x branch here: [(Travis)](https://github.com/TheByKotik/sourcebans-pp/runs/266472846) [(appveyor)](https://ci.appveyor.com/project/TheByKotik/sourcebans-pp/builds/28224445)
For PR here: [(Travis)](https://github.com/TheByKotik/sourcebans-pp/runs/266473745) [(appveyor)](https://ci.appveyor.com/project/TheByKotik/sourcebans-pp/builds/28224456)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by rumblefrog** [comment]
While you at it, can you remove 1.8 from the build matrix and update it to build against the newest SM development version (1.11) and allow it to fail.

**Comment by TheByKotik** [comment]
Updated SM versions and i'm added matrix for  AppVeyor.

(It's so fun. I did this changes in last night and in three hours before when i'm start RP, Alliedmodders have decided bump version)

**Review by rumblefrog — APPROVED** [review]

**Comment by TheByKotik** [comment]
> While you at it, can you remove 1.8 from the build matrix and update it to build against the newest SM development version (1.11) and allow it to fail.

Done and tested.

Results with test error: [(Travis)](https://github.com/TheByKotik/sourcebans-pp/runs/266508624) [(appveyor)](https://ci.appveyor.com/project/TheByKotik/sourcebans-pp/builds/28225062)

**Comment by Bara** [comment]
Why we need both (travis and appveyor)?

**Comment by Bara** [comment]
We can work with github actions and "[runs-on](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idruns-on)" for compiling under linux and windows.

**Comment by rumblefrog** [comment]
We could always move to Github's actions down the road; as of right now Github's action is still in a premature state, at least from my experience trying to use it in a Golang project.

**Comment by CrazyHackGUT** [comment]
I already setuped GitHub Actions for own periodically building plugins. You can try "rewrite" my config.
https://github.com/CrazyHackGUT/sm-uas/blob/master/.github/workflows/blank.yml

**Comment by rumblefrog** [comment]
There are a few issues that I'm waiting on to be resolved with actions, so we can potentially have multi-workflow builds and jobs for this repo and the doc repo.

**Upload Artifact**
- https://github.com/actions/upload-artifact/issues/3
- https://github.com/actions/upload-artifact/issues/21
- https://github.com/actions/upload-artifact/issues/7
- https://github.com/actions/upload-artifact/issues/20

**Download Artifact**
- https://github.com/actions/download-artifact/issues/3

- Build cache is not available as of yet


Github Universe 2019 is about a month away; I suspect by then it'll be out of beta.

**Review by Groruk — APPROVED** [review]

**Comment by Bara** [comment]
@rumblefrog or disable artifact uploads at the beginning. and just compiling the plugins to get the logs.

**Pull request merged**
