### PR TITLE
Migrate Travis to the new container-based infrastructure

### PR DESCRIPTION
**Pull request by winstliu**
:racehorse: :dash: :zap: Builds now start 3000% faster!
Replaces the very broken PR #15.

### CODE REVIEW

**Comment by winstliu** [comment]
The `env:` is also gone because there's really no point when it's being used a whole once.  So I inlined it.

**Comment by sarabveer** [comment]
We need the env: becuase we test build with many different SM versions.

Hey, I just remembered, who removed 1.6.3?

**Comment by winstliu** [comment]
1.6.3 wasn't there when I first edited.  It's not in the master branch either :P.
So which versions specifically do you want to be included?

**Comment by sarabveer** [comment]
1.7.0 and 1.6.3

And when 1.8.0 comes out, I'll add that too.

**Comment by winstliu** [comment]
Done!

**Comment by sarabveer** [comment]
One last thing before I merge. Can you replace $VERSION with $SOURCEMOD

**Comment by winstliu** [comment]
:heavy_check_mark:

**Pull request merged**
