### PR TITLE
✨ Discord Forward Hook

### PR DESCRIPTION
**Pull request by rumblefrog**
## Description

Listens for forward `SBPP_OnBanPlayer` and `SBPP_OnReportPlayer` and sends it to Discord's webhook endpoint(s)

Requires SteamWorks & SMJansson to be installed

## Motivation and Context

Following the broad trend of Discord users, thought it might benefit a lot of users

## How Has This Been Tested?

- SBPP's Main, Report & Discord Plugin with the latest commit on this branch
- Sourcemod 1.8.6041
- SteamWorks Git 126
- SMJansson 2.3.1.3

## Screenshots (if appropriate):
Ban
Report

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by rumblefrog** [comment]
For release which ships precompiled binary, it should ship within the `disabled` folder as it requires additional dependency and convars to setup and not everyone is going to have it.

**Comment by CrazyHackGUT** [comment]
> SteamWorks

SteamWorks have problems with sending HTTP requests. Sometimes with small chance it starts sending the same request thousands of times.
I implemented similar module with using `REST in Pawn` a 9 months ago.
default
default
https://github.com/CrazyHackGUT/Discord/blob/master/addons/sourcemod/scripting/discord_sb.sp

**Comment by rumblefrog** [comment]
> Sometimes with small chance it starts sending the same request thousands of times.

Is there an issue registered with this? I personally never experienced this.

**Comment by CrazyHackGUT** [comment]
Nope, but one my friend encountered this. Sometimes him plugin "arranges DDoS", and one game server sends 1000+ requests on him server. 
img

**Comment by sarabveer** [comment]
@KyleSanderson

**Comment by Groruk** [comment]
>For release which ships precompiled binary, it should ship within the disabled folder as it requires additional dependency and convars to setup and not everyone is going to have it.

Theoreticaly we could move the PR into it's own repo and make it an optional extension for SourceBans++ that way. Just like the DonationControl++ is an optional extension for the webpanel and has it's own repo.

**Review by Groruk — APPROVED** [review]

**Comment by KyleSanderson** [comment]
???

If there's an issue with SteamWorks.ext this is the first time in 4 years anyone has mentioned it. If this is a real issue create a test case and actually file a bug. I can't read russian glyphs and there's zero code.

Rest in Pawn to my knowledge still segfaults like crazy and has a bunch of race conditions; but dealers choice.

**Comment by CrazyHackGUT** [comment]
I forked Rest in Pawn half-year ago, and fixed this segfault.

**Comment by rumblefrog** [comment]
Closing this in favor of a separate repo: https://github.com/sbpp/discord-forward

**Pull request closed without merging**
