### PR TITLE
Add Kick Option to sleuth actions options

### PR DESCRIPTION
**Pull request by CeptForHer**
## Description
Edit **sm_sleuth_actions** description for extra option to kick instead of ban or notify
Add new **#define LENGTH_KICK** for kick action
Add in **LENGTH_KICK** case to **SQL_CheckHim** function

Added new translation to sleuth_phrases called **sleuth_kicktext**

## Motivation and Context
Gives server owners the ability to only kick the user from the server instead of fully ban them, giving them more insight as to why they cannot join on an alternate account.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Review by TheByKotik — APPROVED** [review]
I vote for. This works and why not.

**Review by Groruk — APPROVED** [review]

**Comment by m0rbit1989** [comment]
error ;(

L 08/23/2020 - 11:07:59: [SM] Exception reported: String formatted incorrectly - parameter 4 (total 3)
L 08/23/2020 - 11:07:59: [SM] Blaming: sbpp_sleuth.smx
L 08/23/2020 - 11:07:59: [SM] Call stack trace:
L 08/23/2020 - 11:07:59: [SM]   [0] KickClient
L 08/23/2020 - 11:07:59: [SM]   [1] Line 232, D:\sm_1.10\addons\sourcemod\scripting\sbpp_sleuth.sp::SQL_CheckHim

**Comment by CeptForHer** [comment]
@Groruk is this good to merge or is there an issue in need of fixing?

**Comment by crashzk** [comment]
I believe it would be interesting to apply this change to the option to ban groups and friends that you have on the panel.
image
Option to just kick them would be perfect too.

**Pull request merged**
