### PR TITLE
integrated comms in checker plugin

### PR DESCRIPTION
**Pull request by DataWorm**
As it was already mentioned in #188 this merge request adds support for comms to the checker plugin. So it does add the command sm_listcomms and also shows the amount of comms (if any) when a player joins. Code was successfully tested on our servers, all features seems to work just fine as expected.

### CODE REVIEW

**Comment by rumblefrog** [comment]
Good job on bringing up forgotten issues.

**Comment by sneak-it** [comment]
This is awesome, thank you. Tested and working well across multiple servers, completely error-free. Incredibly helpful!

**Comment by sarabveer** [comment]
We don't really need backwards compatibility for this command.

**Review by Groruk — APPROVED** [review]

**Comment by SkippYSB** [comment]
Good job! Great feature. 
I have a problem though after i updated the sourcebans plugins with this new versions. On several game servers when administrators ban via menu the menu just disappears without any action, nothing in error logs  either. Is there any context? Still works via commands in-game. This problem occurs on both CS:S/CS:GO. SM 1.8

**Comment by DataWorm** [comment]
I don't think it is related to this ticket cause we only made changes on the checker plugin that doesn't contain code for ban menu nor does it create any bans. Anyway maybe you can tell the exact version you are using now and especially the version you used before if you still know that. That could help to identify the commits in which plugins got modified.

**Comment by SkippYSB** [comment]
Okay, thank you for a quick reply.
The old version i used was the first commit from 1.6.2, now i use the commit where you updated the checker. When i updated i just downloaded the SourceBans++ 1.6.3 - PRE.

Edit:
Shall i try go back to 1.6.2 without changing checker?

**Comment by DataWorm** [comment]
Guess that might be a good test. Checked the history and most likely that commit might be related to your issue:
https://github.com/sbpp/sourcebans-pp/commit/8518f3129fcdc9e8ef46a5c5e5ad7319e98136e6#diff-de25bbf1235c858d4088ab16c0f45aed

**Comment by SkippYSB** [comment]
Test = success. The problem is now solved. Yes probably the reason, thank you for your time and help!

**Pull request merged**
