### PR TITLE
Attempt to Fix Sourcecomms

### PR DESCRIPTION
**Pull request by stickz**
Revert 'decl' keyword to 'new' for reason variables. 

Possible fix for reason issue, shouldn't hurt anything to merge.

### CODE REVIEW

**Comment by asherkin** [comment]
Don't use `decl`, put them all back to `new`.

This is exactly why `decl` has been removed from SourcePawn, it's a major source of bugs when people use it without understanding.

**Comment by Sarabveer** [comment]
Replace `decl` with `new` on sourcebans.sp, sbchecker.sp, SourceSleuth.sp, sb_admcfg.sp.

I will merge when those commits are added

**Comment by stickz** [comment]
I wish those issues were just reported in compile warnings. I think the lack of understanding about that feature comes from letting plugins compile without a warning about improper syntax.

**Comment by asherkin** [comment]
A compiler warning for what? `decl` is exactly YOU telling the compiler that you know better than it that the variable doesn't need initialisation - if you then go and assume the variable is in a consistent state... well that's on you.

**Pull request merged**
