### PR TITLE
Merge of format changes

### PR DESCRIPTION
**Pull request by galexrt**
This PR re-formats most files to use mostly PEAR styling syntax and 4 spaces as intent.

### CODE REVIEW

**Comment by galexrt** [comment]
**Note**: Merging directly as the only thing changed is the format/style of the code.

**Comment by sarabveer** [comment]
Why 4 spaces, TAB FOR LYFE!

**Comment by galexrt** [comment]
@Sarabveer http://programmers.stackexchange.com/a/66 ;)

P.S. We can change it later again, but as you can see from the link above it is in some ways better.

**Comment by sarabveer** [comment]
lol, it was a joke @galexrt

**Pull request merged**
