### PR TITLE
Fix Comms, Nasty Issue (LOL)

### LINKED ISSUE #704: Unsilence players: Exception reported: Invalid data pack position, 16 is out of bounds (6)
L 10/18/2020 - 17:11:14: [SM] Exception reported: Invalid data pack position, 16 is out of bounds (6)
L 10/18/2020 - 17:11:14: [SM] Blaming: sbpp_comms.smx
L 10/18/2020 - 17:11:14: [SM] Call stack trace:
L 10/18/2020 - 17:11:14: [SM]   [0] DataPack.Position.set
L 10/18/2020 - 17:11:14: [SM]   [1] Line 1513, sbpp_comms.sp::Query_UnBlockSelect

**Reproduece:**
1. !unsilence
2. Select player
3. Done

### LINKED ISSUE #717: Error databack
What are the steps to reproduce this issue?
-------------------------------------------
1. I don't know.

What happens?
-------------
Error logs
L 01/20/2021 - 19:38:56: [SM] Exception reported: Invalid data pack position, 16 is out of bounds (6)
L 01/20/2021 - 19:38:56: [SM] Blaming: sbpp_comms.smx
L 01/20/2021 - 19:38:56: [SM] Call stack trace:
L 01/20/2021 - 19:38:56: [SM]   [0] DataPack.Position.set
L 01/20/2021 - 19:38:56: [SM]   [1] Line 1513, C:\Users\LAPTOP\Desktop\compiler_6499\sbpp_comms.sp::Query_UnBlockSelect

Any logs, error output, etc.?
----------------------------
L 01/20/2021 - 19:38:56: [SM] Exception reported: Invalid data pack position, 16 is out of bounds (6)
L 01/20/2021 - 19:38:56: [SM] Blaming: sbpp_comms.smx
L 01/20/2021 - 19:38:56: [SM] Call stack trace:
L 01/20/2021 - 19:38:56: [SM]   [0] DataPack.Position.set
L 01/20/2021 - 19:38:56: [SM]   [1] Line 1513, C:\Users\LAPTOP\Desktop\compiler_6499\sbpp_comms.sp::Query_UnBlockSelect

What versions of software are you using?
----------------------------------------
**Operating System:** Linux
**SourceBans++ Version:** 1.7.0
**SourceMod Version:** 1.10.0 - build 6502
**MetaMod Version:** 1.11.0 - build 1143

### PR DESCRIPTION
**Pull request by ClaudiuHKS**
I can't understand how it hasn't been fixed by now.

### CODE REVIEW

**Comment by The-Doggy** [comment]
I'm guessing it hasn't been fixed since it isn't actually an issue as the TempUnBlock function resets the DataPack before doing anything else with it (LOL)

**Comment by TheByKotik** [comment]
> I'm guessing it hasn't been fixed since it isn't actually an issue as the TempUnBlock function resets the DataPack before doing anything else with it (LOL)

Actually he right.
Here: https://github.com/sbpp/sourcebans-pp/blob/2dca124299f4690fb61c9933bd3485ae16d1b9a0/game/addons/sourcemod/scripting/sbpp_comms.sp#L1514
And here: https://github.com/sbpp/sourcebans-pp/blob/2dca124299f4690fb61c9933bd3485ae16d1b9a0/game/addons/sourcemod/scripting/sbpp_comms.sp#L1519
Plugin write cell on position. With 16 it's corrupt reason string in datapack. Third cell is type:
https://github.com/sbpp/sourcebans-pp/blob/2dca124299f4690fb61c9933bd3485ae16d1b9a0/game/addons/sourcemod/scripting/sbpp_comms.sp#L2531

...
Actually... For what pass DataPack in function and unpack it's again? I think we must pass normal params in this function.

**Comment by The-Doggy** [comment]
Oh yeah, my bad. His pull request just sounded super condescending to me so I wanted to be super condescending back :p 
But yeah normal params could be used instead of DataPack here if need be, would save having to declare variables for them inside the function at least.

**Comment by ClaudiuHKS** [comment]
It was throwing error logs. I hate seeing error logs in my logs folder.
It only happened for !ungag !unsilence or !unmute.

**Comment by TheByKotik** [comment]
Wrong.
Value must be `2`. My mistake. Positions start from `0`.
Actually this code can be removed. 
https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L1393
https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L1425
https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L1499-L1523
This checks always `false`:
https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L1512
https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L1517
Because `b_success == true` only here:
https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L1425
But if `target != 0` (second check on 1499 line) called this function above:
1. [PerformUnMute(target);](https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L1433)
2. [stock void PerformUnMute(int target)](https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L2963)
3. [MarkClientAsUnMuted(target);](https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L2965)
4. [stock void MarkClientAsUnMuted(int target)](https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L2855)
5. [g_MuteType[target] = bNot;](https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L2857)

(Almost same trace for PerformUnGag)
And checks never pass.
If any magic forced this checks passed, we have new error: `DataPack` closed in `TempUnBlock()` and new stacktrace [here](https://github.com/sbpp/sourcebans-pp/blob/39ca1c51e56a81f0ec3abe1e3f4a1cd94d8caa65/game/addons/sourcemod/scripting/sbpp_comms.sp#L1527)!
Also i not found any other need to call this code.

**Comment by TheByKotik** [comment]
Сan someone test this version?
https://github.com/TheByKotik/sourcebans-pp/blob/comms-fix-and-cleanup/game/addons/sourcemod/scripting/sbpp_comms.sp
I'm did little changes and tried fix that.
I can't test it in different situations also i haven't time for fix it by another way.
It must resolve this completely for now.

**Review by asherkin — CHANGES_REQUESTED** [review]
Manually casting to DataPackPos like this isn't supported by SM - there is a reason it is a non-coercing type in SourceMod. The position values change regularly between different versions of SM, as they're purely internal references designed to be fetched and later re-used to optimize random access, never persisted.

The correct fix here is to use the matching `Read*` functions to skip over the unwanted data.

**Pull request closed without merging**
