### PR TITLE
Update ban page SteamID check

### PR DESCRIPTION
**Pull request by rumblefrog**
There are users with a much shorter Steam ID, and when attempting to ban those individuals, the check fails.

## Description

Patches length

## Motivation and Context

Fixes an issue with banning users with much shorter Steam ID

https://steamcommunity.com/profiles/76561197960265729 Should be the lowest with 11 characters.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by TheByKotik** [comment]
Why not just do it through XMLHttpRequest (JS Ajax) (or any ajax else)?
```
http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/?key=$SteamAPIKey&steamids=76561197960265729
```
Or (for custom url).
```
http://api.steampowered.com/ISteamUser/ResolveVanityURL/v0001/?key=$SteamAPIKey&vanityurl=$UserVanityURL
```

**Comment by CrazyHackGUT** [comment]
Because for this checks, Steam API key is required.
XMLHttpRequest requires send for user Steam API key. This is insecure, because with key, user can generate GSLT tokens, for example: https://steamapi.xpaw.me/#IGameServersService

**Comment by TheByKotik** [comment]
> Because for this checks, Steam API key is required.
> XMLHttpRequest requires send for user Steam API key. This is insecure, because with key, user can generate GSLT tokens, for example: https://steamapi.xpaw.me/#IGameServersService

No-no-no.
Sorry for my "russian" english.
I'll just print a scheme.
From JS -> /ajax/is-player-valid.php -> call to SteamAPI -> return results to JS.

**Comment by Groruk** [comment]
I wouldn't use steam API calls for ID validation, simply because you would risk running into rate limiting and with akamai's agressive rate limiting and IP blacklisting that would be counter productive (also one of the reasons we use the steam API so sparsely in SBPP)

**Comment by TheByKotik** [comment]
> I wouldn't use steam API calls for ID validation, simply because you would risk running into rate limiting and with akamai's agressive rate limiting and IP blacklisting that would be counter productive (also one of the reasons we use the steam API so sparsely in SBPP)

Anyway, I just suggested using more accurate methods. And maybe display more info about player in ban page.
Okay, I'll know that Steam API is not welcome here.

**Comment by geominorai** [comment]
You could convert and copy the regex from https://github.com/sbpp/sourcebans-pp/blob/v1.x/web/includes/SteamID/SteamID.php#L64 for consistency.

**Review by Groruk — APPROVED** [review]

**Pull request merged**
