### PR TITLE
Fix: #900 & #906

### PR DESCRIPTION
**Pull request by Rushaway**
## Description

Check if the Steamid format is valid by using `isValidID()` from [SteamID.php](https://github.com/sbpp/sourcebans-pp/blob/php81/web/includes/SteamID/SteamID.php#L116)

For #900 I check if isset & is not empty (bcs they can be empty with sm_banip)
For #906 No need to check if set bcs all comms are based on steamid system (no ip supported)
## Motivation and Context

Prevent bad format to break page view.
Give this `$data['steamid'] = 'STEAM_0:0:00000000';` when the `isValid` return false.

## How Has This Been Tested?

For #900 I have a ban in db with `STEAM_ID_STOP_IGNORING_RETVALS` as SteamID in `authid` colume (also tested with a player name..) 
For #906 I have a comms in db with  `STEAM_ID_STOP_IGNORING_RETVALS` as SteamID in `authid` colume 
## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Rushaway** [comment]
nb: [3b1c56b](https://github.com/sbpp/sourcebans-pp/pull/908/commits/3b1c56be167a4d3284954683d00779909fdff564) I was thinking break can be a nice alt, but it's not a suitable solution

**Comment by Hackmastr** [comment]
Hi, thanks for the PR!

I don't think breaking is the correct thing to do, instead check where the steamid is being used and avoid it (either by setting it to null or something similar.

**Comment by Hackmastr** [comment]
Hi, thanks for the PR!

I don't think breaking is the correct thing to do, instead check where the steamid is being used and avoid it (either by setting it to null or something similar.

**Comment by conorab** [comment]
I had this issue as well. I accidentally banned one of the bots in Left 4 Dead 2 in-game and 'BOT' was added to the ban as their SteamID. This was fine pre-1.7 but causes the page to refuse to load now. Fixed by running the following MySQL commands ('sourcebans' being my database):
`USE sourcebans`
`DELETE FROM sb_bans WHERE authid = 'BOT';`

**Pull request merged**
