### PR TITLE
IP Mend

### LINKED ISSUE #187: IP ban players via steamid
Probably simple to do and wouldn't be complicated, and will take a look at a later point, but a cool feature to have would be that if a player is SteamID banned, for example banned after disconnect. At a later point if they reconnect to the server using that SteamID and sourcesleuth detects this, if no IP address is present on the ban, update the ban to include the clients address.

### PR DESCRIPTION
**Pull request by rumblefrog**
## Description

During `VerifyBan` callback, if banned, it will fetch the ban record's IP column. If the column is empty, it will execute another query to mend(fill) it in.

## Motivation and Context

Closes #187 

## How Has This Been Tested?

Tested with the latest `ip-mend` commit with a clean installation on the sourcemod 1.8.6041

## Screenshots (if appropriate):

ip-mend-before
ip-mend-after

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by CrazyHackGUT** [comment]
I think this is a bad idea: to mix the code with obsolete (old) syntax and new one.

**Review by Groruk — APPROVED** [review]

**Comment by Groruk** [comment]
>I think this is a bad idea: to mix the code with obsolete (old) syntax and new one.

To be honest the plugin will need a complete overhaul at some point in the future anyway and the code cant really be more messy than it already is, so mixing syntax should be fine for now.

**Comment by rumblefrog** [comment]
> I think this is a bad idea: to mix the code with obsolete (old) syntax and new one.

You would be right, but I plan to migrate the old syntax to the new ones slowly. This PR will be the start of a gradual migration I suppose

**Comment by CrazyHackGUT** [comment]
> I plan to migrate the old syntax to the new ones slowly

Oh, nice.
You don't plan add the ban feature for the disconnected players?

**Comment by rumblefrog** [comment]
> You don't plan add the ban feature for the disconnected players?

Features will always come after the fixes; but if someone makes an issue on it, I'll look into it

**Pull request merged**
