### PR TITLE
feat: Partial refactoring, fix: #913 #907 #880 #848 #784

### PR DESCRIPTION
**Pull request by Rushaway**
## Description

- Prevent players to avoid comms block issues
- Fix players considered as not verified and cant be muted/gagged
- Fix comms receive from web not applied immediatly
- Create forward when player get unpunished
- Adjust punish forward position
- Optimisation of string read speed comparaison

## Motivation and Context

#913 #907 #880 #848 #784

## How Has This Been Tested?

In production on NiDE.GG since 5+ months
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Neoony** [comment]
getting error when compiling

**Comment by Neoony** [comment]
If I comment that out, it builds


However some error when I mute myself from server console
either with or without reason


but it seems it works and everything looks ok on web

**Comment by Rushaway** [comment]
@Neoony  You got this error because you commented the previous content without adjusting the Datapack, it's solved now. 
Thanks for the review, appreciate it

**Comment by Neoony** [comment]
Yep, Now it builds fine and no more error ingame
Thx

**Comment by Rushaway** [comment]
With this last commit (just pushed), it will prevent the only error I found with the timer handle who can be invalid.

No more issues left for me. Considering as stable.

**Comment by Rushaway** [comment]
@Hackmastr Any review ? 👍

**Pull request merged**
