### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by Rushaway**
## Description

Updating Changelog.md

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by Hackmastr** [comment]
Thank you very much!

**Comment by rumblefrog** [comment]
I'm not up to date with the changes, but looking at the changelog, what warrants the major version bump to 2.x?

**Comment by Rushaway** [comment]
@rumblefrog You would prefer 1.8.0 ? I can make a PR with all files related to it.

**Comment by rumblefrog** [comment]
1.8.x is more fitting; trying to stick with semver versioning, my initial impression seeing 2.x is that it's a breaking change.

**Comment by Rushaway** [comment]
@rumblefrog Here you go.

**Pull request merged**
